spring:

  application:
    name: management-consumer

  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456

  jackson:
    default-property-inclusion: NON_NULL

server:
  port: 8765
  servlet:
    context-path: /shiroAuth


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

#请求处理的超时时间
ribbon:
  ReadTimeout: 120000
  #请求连接的超时时间
  ConnectTimeout: 30000

logging:
  config: classpath:log4j2.xml



